### ISSUE TITLE
Build failes on OpenBSD 6.9 -  error: request for member '_file' in something not a structure or union

### ISSUE THREAD

**Issue by Rot127** [aide/aide#98]
Build on OpenBSD 6.9 fails for `aide v0.17.3`. The `./configure `command was:
`./configure LDFLAGS="-L/usr/local/lib" CFLAGS="-Wl,-R/usr/local/lib" LIBS="-lpcre"  CFLAGS="-I/usr/local/include"`

`make` log:

```
[...]

/usr/local/include/mutils/mhash_config.h:201:1: warning: "PACKAGE_VERSION" redefined
In file included from ./include/db_config.h:25,
                 from ./include/aide.h:27,
                 from src/commandconf.c:22:
./config.h:193:1: warning: this is the location of the previous definition
In file included from /usr/local/include/mutils/mincludes.h:34,
                 from /usr/local/include/mhash.h:6,
                 from ./include/db_config.h:87,
                 from ./include/aide.h:27,
                 from src/commandconf.c:22:
/usr/local/include/mutils/mhash_config.h:213:1: warning: "VERSION" redefined
In file included from ./include/db_config.h:25,
                 from ./include/aide.h:27,
                 from src/commandconf.c:22:
./config.h:247:1: warning: this is the location of the previous definition
src/commandconf.c: In function 'db_input_wrapper':
src/commandconf.c:229: warning: dereferencing 'void *' pointer
src/commandconf.c:229: error: request for member '_file' in something not a structure or union
src/commandconf.c:230: warning: dereferencing 'void *' pointer
src/commandconf.c:230: error: request for member '_file' in something not a structure or union
*** Error 1 in . (Makefile:743 'src/commandconf.o')
*** Error 2 in /home/user/aide-0.17.3 (Makefile:512 'all')
```

**Comment by hvhaugwitz** [comment]
Unfortunately I don't have access to an OpenBSD system, hence I cannot reproduce your issue.

Can you please apply the following change and try again?
```
diff --git a/include/db_config.h b/include/db_config.h
--- a/include/db_config.h
+++ b/include/db_config.h
@@ -174,7 +174,7 @@ typedef struct database {
     int linenumber;
     char *linebuf;
 
-    void *fp;
+    FILE *fp;
 #ifdef WITH_ZLIB
     gzFile gzp;
 #endif

```

**Comment by Rot127** [comment]
This fixed it. Thank you for your quick help!
