### ISSUE TITLE
AIDE fails to build on Alpine 3.23

### ISSUE THREAD

**Issue by quebelo** [aide/aide#216]
### Description

After upgrading Alpine from 3.20 to 3.23, AIDE failed to build on Alpine with the following error:

`make  all-am`
`make[1]: Entering directory 'aide-0.18.8'`
`gcc -DHAVE_CONFIG_H -I. -I./include  -I. -I./include -I./src -I./src  -D_GNU_SOURCE -W -Wall -g          -pthread    -g -O2  -fPIE -DPIE -Wundef -Wmissing-format-attribute -Wshadow -Wlogical-op -MT src/aide-aide.o -MD -MP -MF src/.deps/aide-aide.Tpo -c -o src/aide-aide.o `test -f 'src/aide.c' || echo './'`src/aide.c`
`In file included from src/aide.c:52:`
`./include/getopt.h:136:12: error: conflicting types for 'getopt'; have 'int(void)'`
`  136 | extern int getopt ();`
`      |            ^~~~~~`
`In file included from /usr/include/fortify/unistd.h:23,`
`                 from src/aide.c:36:`
`/usr/include/unistd.h:127:5: note: previous declaration of 'getopt' with type 'int(int,  char * const*, const char *)'`
`  127 | int getopt(int, char * const [], const char *);`
`      |     ^~~~~~`
`make[1]: *** [Makefile:858: src/aide-aide.o] Error 1`
`make[1]: Leaving directory 'aide-0.18.8'`
`make: *** [Makefile:591: all] Error 2`

It turns out that Alpine 3.23 replaces GCC version 13 with GCC version 15.

As a workaround, we were able to build by setting the C-standard back to GNU17 (default spec of GCC 13):

`cd aide-0.18.8`
`./configure CFLAGS="-std=gnu17"`
`make & make install`

Same problem happens with AIDE 0.19.2.

### How to reproduce the issue?

On Alpine Linux 3.23:

`apk add build-base bison flex pcre2-dev libgcrypt-dev`
`curl -L https://github.com/aide/aide/releases/download/v0.18.8/aide-0.18.8.tar.gz | tar xvfz -`
`cd aide-0.18.18`
`./configure`
`make & make install` 

### Which version of AIDE are you using?

Both versions 0.18.8 and 0.19.2.

### How did you install AIDE?

manual build from release tarball

### What's your operating system?

Alpine Linux 3.23
